// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpmocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewDoer creates a new instance of Doer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Doer {
	mock := &Doer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Doer is an autogenerated mock type for the Doer type
type Doer struct {
	mock.Mock
}

type Doer_Expecter struct {
	mock *mock.Mock
}

func (_m *Doer) EXPECT() *Doer_Expecter {
	return &Doer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type Doer
func (_mock *Doer) Do(request *http.Request, v any) error {
	ret := _mock.Called(request, v)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, any) error); ok {
		r0 = returnFunc(request, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Doer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type Doer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - request *http.Request
//   - v any
func (_e *Doer_Expecter) Do(request interface{}, v interface{}) *Doer_Do_Call {
	return &Doer_Do_Call{Call: _e.mock.On("Do", request, v)}
}

func (_c *Doer_Do_Call) Run(run func(request *http.Request, v any)) *Doer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Doer_Do_Call) Return(err error) *Doer_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Doer_Do_Call) RunAndReturn(run func(request *http.Request, v any) error) *Doer_Do_Call {
	_c.Call.Return(run)
	return _c
}
